### ISSUE TITLE
Might be a good idea to indicate when an action is used after it's run out of uses

### ISSUE THREAD

**Issue by xdy** [reyzor1991/foundry-vtt-pf2e-action-support#1]
E.g. something like this:
diff --git a/src/main.js b/src/main.js
index 432fecb..181dee9 100644
--- a/src/main.js
+++ b/src/main.js
@@ -234,6 +234,9 @@ Hooks.on('preCreateChatMessage',async (message, user, _options, userId)=>{
                     "system.frequency.value": _obj?.system?.frequency?.value - 1
                 });
             }
+            if (_obj?.system?.frequency?.value === 0) {
+                sendNotificationChatMessage(message.actor, `Action sent to chat with 0 uses left.`);
+            }
         }
     }
 });

**Comment by reyzor1991** [comment]
Added in 0.0.7

https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/6688366/74f08d84-434f-4d7d-9f8a-d57cc7f2b584
