### ISSUE TITLE
Request: Observe Godless Healing

### ISSUE THREAD

**Issue by Pyroman2xxx** [reyzor1991/foundry-vtt-pf2e-action-support#10]
Would it be possible to have Treat Wounds and Battle Medicine observe the feat Godless Healing?

Text of the feat:
You recover an additional 5 Hit Points from a successful attempt to Treat your Wounds or use Battle Medicine on you. After you or an ally use Battle Medicine on you, you become temporarily immune to that Battle Medicine for only 1 hour, instead of 1 day.

**Comment by Pyroman2xxx** [comment]
Thank you for the quick addition!

I Tested the new Godless Healing addition and the cooldown works great but it is not adding the +5 Hit Points to the healing.

**Comment by reyzor1991** [comment]
+5 Hit Points to the healing — it's part of pf2e macro, I am preparing change for it

**Comment by reyzor1991** [comment]
I hope that + 5 hp would be in next release

**Comment by Pyroman2xxx** [comment]
Thank you very much!

**Comment by reyzor1991** [comment]
@Pyroman2xxx you can use this rule for now. Add it to godless feat

```
{
  "key": "FlatModifier",
  "predicate": [
    "action:treat-wounds"
  ],
  "selector": "healing-received",
  "value": 5
}
```
