### ISSUE TITLE
pf2e Work Bench Breath Weapon Recharge Effect stops all Strikes from Rolling when pf2e Action Support is enabled

### ISSUE THREAD

**Issue by Aeristoka** [reyzor1991/foundry-vtt-pf2e-action-support#11]
1. Click Breath Weapon to chat
2. Breath Weapon Recharge Reminder Pops up (from pf2e workbench)
![image](https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/7988297/f2696b54-d0b3-42f0-a873-aa4dbb5bf42c)

4. Attempt to roll a strike
5. pf2e Action Support stops all strikes from rolling
![image](https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/7988297/96d7ed84-0d53-4ce5-9fa1-26ff7256cf6f)

**Comment by Aeristoka** [comment]
May have been fixed here: https://github.com/xdy/xdy-pf2e-workbench/commit/dc66a07434da77b4e0f40af4e4e719555637576e

**Comment by reyzor1991** [comment]
How to correct reproduce steps, because I can't get this effect

**Comment by reyzor1991** [comment]
I reproduced, but this issue happens also if only workbench is active, so this module not related with Breath Weapon issue
