### ISSUE TITLE
Feature Request - Drained Condition Summoner/Eidolon

### ISSUE THREAD

**Issue by ottyn** [reyzor1991/foundry-vtt-pf2e-action-support#12]
Add the Drained condition to sync between Summoner and Eidolon.  RAW if the Eidolon received the Drained condition, since it effects max HP, it will also pass to the Summoner and vise versa.

**Comment by reyzor1991** [comment]
Added in last version. Drained always added to summoner and effect to Eidolon, it's need to save logic of Eidolon max HP
