### ISSUE TITLE
Soothe spell effect applying twice

### ISSUE THREAD

**Issue by this-gavagai** [reyzor1991/foundry-vtt-pf2e-action-support#13]
First, thanks for this fantastic module. It has really improved the quality of our in person games dramatically.

I'm running into an issue with Soothe. During a normal casting process, the spell effect (bonus against mental effects) is consistently applied twice: first, it gets applied when the spell is cast, and second, it gets applied when the "Heal" button is clicked. I can reproduce this consistently on a clean install with no other modules. See video below for details.

https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/9303694/1e01c8e9-7f27-40a3-9634-e14933022017

**Comment by reyzor1991** [comment]
Fixed
