### ISSUE TITLE
The effect of Bane allways applies effect (feature request/bug)

### ISSUE THREAD

**Issue by Fabrice-Schoeneberger** [reyzor1991/foundry-vtt-pf2e-action-support#14]
When you cast Bane you get the bane effect on the casting charakter. This effect applies the -1 to attack rolls to all Enemy charakters. Normaly those enemies get a Will Save to not be affected. I don't know if its possible to make this save automaticly with appling the effect/being the aura, but maybe that is something possible for the future.
For now maybe make an option the the module menu to turn individual effects off or even edit then on the local end

**Comment by reyzor1991** [comment]
I think it's possible, I will add immunity to bane

**Comment by reyzor1991** [comment]
Done

**Comment by Fabrice-Schoeneberger** [comment]
It doesn't do the auto roll for me tho. I only the new immunity effect. That works as intended when manually applied. So that is nice

**Comment by reyzor1991** [comment]
socketLib is active? Locally for me all is ok.

**Comment by Fabrice-Schoeneberger** [comment]
socketLib is on and Alliance is on enemy. It does just apply the effect, but only to opposition of the respective groupe

**Comment by reyzor1991** [comment]
Yes, if PC casts - effect should apply to opposition
If NPC - to party

**Comment by Fabrice-Schoeneberger** [comment]
Hmmm ok now something diffent has happend. When I cast the spell from a player acc, all enemies within 5 ft. make a save. The ones that make it get the immune effect, the other ones get nothing. not even the normal bane effect.
Also the rolls are made from the player, not the DM so the player can see all rolls and modifiers

**Comment by Fabrice-Schoeneberger** [comment]
The effect also doesn't retrigger a save for all previewesly not affected targets when widening the range.

**Comment by Fabrice-Schoeneberger** [comment]
Also the bless spell is broken and doesn't apply the effect anymore ... I don't know if I can reproduce the bug better. If I get something I write again

**Comment by reyzor1991** [comment]
https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/6688366/fe126542-bbbd-4169-af03-a2045bf5a44d

**Comment by reyzor1991** [comment]
Bless add aura from workbench

**Comment by reyzor1991** [comment]
<img width="612" alt="Screenshot 2023-08-20 at 23 40 25" src="https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/6688366/540a5352-8be7-4690-8b07-23bf8b9fde6a">

**Comment by Fabrice-Schoeneberger** [comment]
Ok I got it working as intended. I needed to restart the server for it. Now everything works.
Now the only things left are:
1. Make it so that the autosavingthrows are made by the GM, or at least use his roll settings, so that the rolls and modifiers are possibly hidde from the players
2. New enemies entering the area for the first time, either because the area expanded or someone moves, need to make the saving throw
3. Maybe (just maybe) make the icon for the immunity and the icon for the bane effect slight different to better see which enemy did it and which didn't

**Comment by reyzor1991** [comment]
Will change roll to blind
I will find a new icon
When aura radius are changed – all who don't have immunity or bane should roll again
But if npc move in radius — now it's hard to track

**Comment by Fabrice-Schoeneberger** [comment]
Yea so much I thought with the hard to track. I mean ... I'm new to working with effects but I immagine that you could make something like: When a character that failed the save leaves the area, you could remove the normal effect and give him an effect instead that just says "failed save to bane". When a character then enters the area you could check if it has this effect. If yes take it away an apply the bane effect. If no and also no immune, make save, then handle outcome. I think this might be the most elegant solution without confusing ppl too much.

The only thing I'm thinking now is ... how the hell would it be handled if multiple sources cast bane, like 2 PC or 2 NPCs like 2 Mitfit on the first level on gauntlight ...
