### ISSUE TITLE
Hunted Shot macro ignores users "Preview D20 Rolls" settings (bug)

### ISSUE THREAD

**Issue by Fabrice-Schoeneberger** [reyzor1991/foundry-vtt-pf2e-action-support#17]
By default the Preview D20 Rolls is on but if you turn it off, the macro still prompts you with the preview. This doesn't change when you shit click the "Attack" button

**Comment by reyzor1991** [comment]
Could you create a screenshot of settings with this one? Because I can't find this option.

**Comment by Fabrice-Schoeneberger** [comment]
![Screenshot 2023-08-21 150431](https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/64808681/5ece6e47-2b13-439d-8bf2-9427c8da5d8c)
Rightclick on the username and click "User Configuration". Then you see the option

**Comment by reyzor1991** [comment]
Found issue by default, I always skip dialog and not show it for PCs. Will add checking this setting.

**Comment by reyzor1991** [comment]
Fixed next release 0.2.24
