### ISSUE TITLE
double slice should consider critical hits in determining which attack has precision damage applied

### ISSUE THREAD

**Issue by surged20** [reyzor1991/foundry-vtt-pf2e-action-support#18]
createDataDamageOnlyOnePrecision looks at the magnitude of a critical hit without considering 2x damage when determining with attack to apply precision damage to
https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/blob/4e72050fd6be1e455f248c08b62bb2665e1f2443/src/main.js#L855

Since the player is permitted to add the precision damage to the attack of their choice, precision damage should be applied to the critical hit in the event that one attack crits and the other is a normal hit. Here is an example of precision damage incorrectly applied to the regular hit.

![image](https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/71271408/4bfbd788-ed49-4cb1-bba0-be2b360335e3)

**Comment by reyzor1991** [comment]
Fixed in 0.2.26
