### ISSUE TITLE
Treat Wounds/Battle Medicine no longer applying immunity

### ISSUE THREAD

**Issue by Pyroman2xxx** [reyzor1991/foundry-vtt-pf2e-action-support#19]
At some point in the last week or two, Treat Wounds and Battle Medicine stopped applying the immunity effects to the target.

There are no console errors.

I thought that it might be a conflict with another add-on but I just created a brand new world and tested it. Demoralize, for example, applies that immunity but Treat Wounds/BM do not. I did not test with fully created characters. I just created actors, gave one the Medicine skill and the Treat Wounds action for testing.

**Comment by reyzor1991** [comment]
fixed
