### ISSUE TITLE
[Bug] Feint Not applying effect to target

### ISSUE THREAD

**Issue by cadowtin** [reyzor1991/foundry-vtt-pf2e-action-support#2]
![image](https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/79132112/72b9523d-e0bb-445c-b19c-53726d4ed8b5)
![image](https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/79132112/5750258d-7650-4940-b3fb-54d620754568)

Following errors appears when trying to feint as a player (not gm)

**Comment by cadowtin** [comment]
Extra Note, appears to work perfectly fine as the GM, but player usage is what is causing issues

**Comment by reyzor1991** [comment]
Fixed 0.0.17

**Comment by tgog217** [comment]
Critical Success of Feint does not last a round for me. It is removed after the first attack.

**Comment by reyzor1991** [comment]
@tgog217 Yes, it's another bug, I read feint action description incorrectly. I will fix ASASP
