### ISSUE TITLE
some double slice issues

### ISSUE THREAD

**Issue by dharkus5000** [reyzor1991/foundry-vtt-pf2e-action-support#20]
the double slice macro currently doesn't handle correctly the persistent dmg from at least greater flaming runes if both attacks hit, it currently gives the enemy 2d10+2d10 persistent
it also doesn't automatically apply greater crushing effect to the enemy (this i think wasn't happening more widely, and i'm sure it was last week!)
it also wasn't applying the crit spec effects to the enemies when used either, specifically the prone from hammers

**Comment by reyzor1991** [comment]
I know about it
It's an issue of all double damage macro, because in general it's generated message and not damage message

**Comment by reyzor1991** [comment]
<img width="296" alt="Screenshot 2023-09-07 at 16 41 48" src="https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/6688366/36bb6486-3e4e-4acc-b5d7-5f62dec4fd1c">

Crit spec effects—applied
