### ISSUE TITLE
[Bug] Monk Flurry doesn't work with Monastic Archer Stance

### ISSUE THREAD

**Issue by Peach774** [reyzor1991/foundry-vtt-pf2e-action-support#25]
As title - my player can't choose their equipped bow as a weapon for their flurry when in monastic archer stance.

**Comment by reyzor1991** [comment]
Bow should have reload 0, please check it

**Comment by Peach774** [comment]
They're using a composite longbow, but its a modified weapon with additional tags and a changed name. I was able to fix it by tagging it as unarmed which seems logical but also odd that I had to do that.

**Comment by Peach774** [comment]
![image](https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/5171184/03423e5d-296f-4e58-af00-f0505c9885b9)
![image](https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/5171184/a0906b84-c463-4e8d-a561-03f06fb4f599)
Not working unless I add the unarmed trait to the bow - I don't know why

**Comment by Peach774** [comment]
Ok, yeah this seems to be working now - no idea why it was broken.
