### ISSUE TITLE
Battle medicine and Treat wounds immunities

### ISSUE THREAD

**Issue by Suldrun45** [reyzor1991/foundry-vtt-pf2e-action-support#27]
There are a few strange things with the way those immunities are applied to the target of those actions (when using the Workbench macro):
1. The immunity will be set automatically only if the character doesn't have continual recovery.
2. In that case, it's always the Treat wounds immunity that is applied, even if the character used the Battle medicine option in the dropdown.

(tested on a fresh world with no modules except Workbench and PF2e Action Support)

**Comment by reyzor1991** [comment]
There are no immunity if   PC has continual recovery feat because 10 min immunity after start healing with duration 10 min, 
 need to use Battle medicine only during battle
