### ISSUE TITLE
Request: Battlemedicine

### ISSUE THREAD

**Issue by roguedevjake** [reyzor1991/foundry-vtt-pf2e-action-support#3]
Adding the person making the check to the immunity effect's name would be useful, since it only applies to the character who used battle medicine, rather than everyone who uses it (and in my experience it is a feat that is often taken by 2+ characters)

**Comment by reyzor1991** [comment]
There is [Ward Medic](https://2e.aonprd.com/Feats.aspx?ID=864) feat. But it's only for Treat Wounds action, you can't combine with Battle Medicine. If you know feat name it would be great, I not found

**Comment by reyzor1991** [comment]
Current functionality

https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/6688366/9e672214-8cd7-435e-8eee-97e7d3e60f47

As I understood, you want that when any PC use Battle Medicine target get effect like "Effect: Battle Medicine Immunity (Seoni (Level 1))" and PC get "Battle Medicine was used (Merisiel (Level 1))", is it correct?


<img width="804" alt="Screenshot 2023-07-17 at 22 04 36" src="https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/6688366/bc976aee-a42d-4605-9538-fb60dfac38d3">

<img width="732" alt="Screenshot 2023-07-17 at 22 04 46" src="https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/6688366/d64120ef-ba16-4e06-9562-11b6f359624a">

**Comment by uniwars** [comment]
I think that was his request, battle medecine's immunity is per PC, treat wounds immunity is global and its duration is depending if the healer had continual recovery or not

**Comment by reyzor1991** [comment]
https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/6688366/8d9ae63b-552c-45eb-aca1-61408453e85f

**Comment by uniwars** [comment]
I don't understand the clip :

It's not in combat so it's treat wounds, not battle medicine here, so the treat wounds immunity effect they give should be global

Medic dedication gives the chance to use "battle medicine" on someone already immune to the healer's battle medicine (immunity which last 1 day). One battle medicine which bypass the immunity by day, or by hour when master.

Saying that there is still the option to use "battle medicine" out of combat, but that's not what the clip show I think

The pf2e workbench macro for treat wounds/battle medicine already handles immunities effect per PC/ some feats integration (idk if there are not implemented) and offer the choice between treat wounds and battle medicine. Idk if it's possible but running the macro when using the action should be a nice way to automate it

**Comment by roguedevjake** [comment]
> As I understood, you want that when any PC use Battle Medicine target get effect like "Effect: Battle Medicine Immunity (Seoni (Level 1))" and PC get "Battle Medicine was used (Merisiel (Level 1))", is it correct?

Sorry no, you can close the issue. I was sure last time I tried it that when using battle medicine it just put an effect saying "Effect: Battle Medicine Immunity" without the name, but trying it out now it does indeed put the name in brackets and that is fine.

Sorry for the confusion.
