### ISSUE TITLE
Summoner Eidolon HP link

### ISSUE THREAD

**Issue by Necr0zzz** [reyzor1991/foundry-vtt-pf2e-action-support#34]
Hey, it seems to be missing all of a sudden and i haven't found anything about it. 
Was it removed forever?

**Comment by reyzor1991** [comment]
@Necr0zzz It was moved to separated module

https://github.com/reyzor1991/pf2e-eidolon-helper

**Comment by Necr0zzz** [comment]
yeah thanks found the changelog 5 mins after posting... sorry
