### ISSUE TITLE
[Feature Request] Turn off Specific Actions

### ISSUE THREAD

**Issue by 117ksk** [reyzor1991/foundry-vtt-pf2e-action-support#41]
It would be really useful to be able to ignore specific actions from being automatically handled by this module. For example, depending on other modules in use, Guidance might get applied automatically twice to the same target in the same casting. 

A way to "turn off" specific spells/actions for this module would make the compatibility much nicer with other modules.

**Comment by reyzor1991** [comment]
It would be possible with https://foundryvtt.com/packages/pf2e-automations, with this module it's impossible
