### ISSUE TITLE
Sorting attacks on Doubleslice macro

### ISSUE THREAD

**Issue by JamzTheMan** [reyzor1991/foundry-vtt-pf2e-action-support#49]
Could the double slice macro account for sorting and prefer Agile weapons for second strike?

e.g. +2 ‎Striking‎‎ ‎Wounding Rapier / +2 Striking Fearsome Shortsword currently sort alphabetically so it always puts the shortsword in the first attack dropdown making the Rapier -2 for not being agile.

Also, after the macro finishes, it leaves the "Double Slice Second Attack" checkbox toggle on and so you have to uncheck it each time if you want to do a third attack or a different attack next round. Preferably this would be unchecked after the macro is finished.

**Comment by reyzor1991** [comment]
https://github.com/user-attachments/assets/5d9cb207-c7f3-48b3-ac85-44438fc52cb9

Check console, maybe some errors
