### ISSUE TITLE
Bug with Shield effect

### ISSUE THREAD

**Issue by uniwars** [reyzor1991/foundry-vtt-pf2e-action-support#5]
Hi, when casting shield it will add both the shield effect and the shield immunity and that will break the token's condition HUD :

![image](https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/65986545/4ac1acb6-7b1c-431e-a793-75cd1cc648ca)

spell immunity cannot be removed by right clicking, F5 is required :

![image](https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/65986545/a64c5811-3be7-462a-9a65-7136571a605d)

**Comment by reyzor1991** [comment]
Fixed 0.0.20
