### ISSUE TITLE
[Feature Request] Goading Feint

### ISSUE THREAD

**Issue by uLotUu** [reyzor1991/foundry-vtt-pf2e-action-support#50]
Any chance to add automation for this feature for Swashbuckler? Or at least disable auto Feint (and maybe adding a second effect to chat) if he has the feat? Ideally there would be a choice for a player "which Feint would you like to use?" or smth.

**Comment by reyzor1991** [comment]
Disabling rules is part of PF2e Automations, for this module is impossible
