### ISSUE TITLE
Flurry of Blows only applies Sneak Attack once

### ISSUE THREAD

**Issue by MildlyIncandescent** [reyzor1991/foundry-vtt-pf2e-action-support#51]
When utilizing the Flurry of Blows macro from a Rogue with the Monk archetype, Sneak Attack's precision damage is added to only one of the two Strikes, even in cases where both successfully hit or critically hit an off-guard target.
![image](https://github.com/user-attachments/assets/ab22fc61-2905-472f-b6f2-54cadaa8aa82)
RAW, Sneak Attack should be applied to both Strikes. This issue seems to be as a result of the combinedDamage function.

**Comment by reyzor1991** [comment]
For macros better to use https://foundryvtt.com/packages/pf2e-macros

New macros has better less errors
