### ISSUE TITLE
Shield spell effect isn't heightened

### ISSUE THREAD

**Issue by uniwars** [reyzor1991/foundry-vtt-pf2e-action-support#6]
Hi, the effect which is auto-added when casting the spell is the level 1 version, when I remove it and add it from the spell card I correctly get the heightened effect. (vital beacon might have the same issue)

![image](https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/65986545/3ffdece1-0a5b-4684-9502-acc18ba336c7)

**Comment by reyzor1991** [comment]
Fixed
