### ISSUE TITLE
Request: Pistol Twirl

### ISSUE THREAD

**Issue by Far2Casual** [reyzor1991/foundry-vtt-pf2e-action-support#8]
Pistol Twirl is a (low-level) feat that enables the Pistolero as it allows him to Feint people at a distance. At the moment, the additional Feint support & effects only work on melee attacks. Any possibility this could be extended to range for Pistol Twirl ?👼 

P.S.: love the module :)

**Comment by reyzor1991** [comment]
Pistol Twirl was added, Need to use action for start after it feint and ranged attack will be trigger effect
In example Rogue trigger flat-footed with attack and damage(sneak attack was added) 

0.0.30

https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/assets/6688366/152fb089-4987-4693-a294-fcaaf3a96a6b

**Comment by reyzor1991** [comment]
@Far2Casual If you want, you can post proposal to discord thread
https://discord.com/channels/880968862240239708/1131271396123742339

**Comment by Far2Casual** [comment]
You are awesome ! Thanks !
